dependencies:
  ds18b20:
    url: github.com/toitware/toit-ds18b20
    version: ^2.0.0
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.1.1
  one_wire:
    url: github.com/toitware/toit-1-wire
    version: ^2.1.1
